config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  
  resources :data_mappers
  resources :workflows, only: [:index]
  resources :ingests, only: [:index, :show, :destroy]
  resources :transfers, only: [:index, :show, :destroy]
  resources :reviews, only: [:index, :show, :destroy]
  
  resources :retry_ingest, only: [:show] do
    get ":id", to: "ingests#retry_ingest", on: :collection
  end
  resources :retry_transfer, only: [:show] do
    get ":id", to: "transfers#retry_transfer", on: :collection
  end
  resources :retry_review, only: [:show] do
    get ":id", to: "reviews#retry_review", on: :collection
  end
  resources :notifications
  resources :starts do
    collection do
      get :start_transfer
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users
  resources :users, :controller => 'users'
end

app/models/ingest.rb
class Ingest < ApplicationRecord
end

app/controllers/ingests_controller.rb
class IngestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ingest, only: [:show, :retry_ingest]
  attr_reader :client, :ingest

  # GET /ingests
  def index
    @client = Gush::Client.new
    @ingests = client.all_workflows.select { |wf| wf.class == IngestWorkflow }
  end

  # GET /ingests/1
  def show; end

  # GET /retry_ingest/1
  def retry_ingest
    ingest.continue
    ingest.reload
    respond_to do |format|
      format.html { redirect_to ingest_path, notice: "Ingest #{params[:id]} was sent for a retry." }
      format.json { head :no_content }
    end
  end

  # DELETE /ingests/1
  def destroy
    @client ||= Gush::Client.new
    client.destroy_workflow(client.find_workflow(params[:id]))
    respond_to do |format|
      format.html { redirect_to ingests_path, notice: "Ingest #{params[:id]} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_ingest
      @ingest = IngestWorkflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingest_params
      params.require(:ingest).permit(:status)
    end
end

app/helpers/ingests_helper.rb
module IngestsHelper
  include WorkflowsHelper
end

app/views/ingests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingests</h1>

<% if @ingests.length > 5 %>
  <p>
    <%= link_to 'Goto Transfers', transfers_path %><br />
    <%= link_to 'Goto Reviews', reviews_path %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Ingest</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Status</th>
      <th>Failure info</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% jobs_in_order(@ingests).each do | ingest | %>
      
      <tr>
        <td>
          <%= ingest.id %><br />
          <%= link_to 'Show', :action => "show", :id => ingest.id %>
          </td>
        <td><%= Time.at(ingest.started_at) unless ingest.started_at.blank? %></td>
        <td><%= Time.at(ingest.finished_at) unless ingest.finished_at.blank? %></td>
        <td><%= ingest.status %></td>
        <td>
          <% ingest.jobs.select(&:failed?).sort_by(&:failed_at).each do | job | %>
            Job: <%= job.name %><br />
            &nbsp;&nbsp;Failed at: <%= Time.at(job.failed_at) %><br />
            &nbsp;&nbsp;Message: <%= job.output_payload[:message] if job.output_payload %>
            <% if job.output_payload && job.output_payload[:event] == 'retry' %>
            <br /><br />
            Event state: <%= job.output_payload[:event] %><br />
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Delete', 
             ingest_path(ingest.id), 
             method: :delete, 
             data: { confirm: 'Are you sure you want to delete this ingest?' } %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<p>
  <%= link_to 'Goto Transfers', transfers_path %><br />
  <%= link_to 'Goto Reviews', reviews_path %>
</p>

<br>

app/views/ingests/show.html.erb
<p id="notice"><%= notice %></p>

<table>

  <tbody>
    <tr>
      <td>ID:</td><td><%= @ingest.id %></td>
    </tr>
    <tr>
      <td>Name:</td><td><%= @ingest.class.to_s %></td>
    </tr>
    <tr>
      <td>Status</td><td><%= @ingest.status %></td>
    </tr>
    <tr>
      <td>Started at:</td><td><%= Time.at(@ingest.started_at) unless @ingest.started_at.blank? %></td>
    </tr>
    <tr>
      <td>Finished at:</td><td><%= Time.at(@ingest.finished_at) unless @ingest.finished_at.blank? %></td>
    </tr>
    <tr>
      <td>Total Jobs:</td><td><%= @ingest.jobs.count %></td>
    </tr>
    <tr>
      <td>Enqueued jobs:</td><td><%= count(@ingest, 'enqueued') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Running jobs:</td><td><%= count(@ingest, 'running') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Remaining jobs:</td><td><%= count(@ingest, 'remaining') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Succeeded jobs:</td><td><%= count(@ingest, 'succeeded') %></td>
    </tr>
    <tr>
      <td>Number of Works:</td><td><%= @ingest.number_of_works %> (plus 1 Package)</td>
    </tr>
    <% succeeded_jobs_in_order(@ingest).each do | job |  %>
      <tr>
        <td></td>
        <td>
          <%= job.name %><br />
          <% if job.output_payload %>
            <% job.output_payload.each do | key,value | %>
              <% next if value.blank? %>
              &nbsp;&nbsp;<%= "#{key}: #{value}" %><br />
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>Failed jobs:</td><td><%= @ingest.jobs.select(&:failed?).count %></td>
    </tr>
    <% failed_jobs_in_order(@ingest).each do | job | %>
      <tr>
        <td></td>
        <td>
          <%= job.name %><br />
          <% if job.output_payload %>
            <% job.output_payload.each do | key,value | %>
              <% next if value.blank? %>
              &nbsp;&nbsp;<%= "#{key}: #{value}" %><br />
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to 'Refresh', review_path %> | 
<% unless @ingest.finished? %>
  <%= link_to 'Retry', retry_ingest_path(@ingest.id) %> | 
<% end %>
<%= link_to 'Delete', 
             review_path(@ingest.id), 
             method: :delete, 
             data: { confirm: 'Are you sure you want to delete this ingest?' } %> | 
<%= link_to 'Back', ingests_path %>