config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  
  resources :data_mappers
  resources :workflows, only: [:index]
  resources :ingests, only: [:index, :show, :destroy]
  resources :transfers, only: [:index, :show, :destroy]
  resources :reviews, only: [:index, :show, :destroy]
  
  resources :retry_ingest, only: [:show] do
    get ":id", to: "ingests#retry_ingest", on: :collection
  end
  resources :retry_transfer, only: [:show] do
    get ":id", to: "transfers#retry_transfer", on: :collection
  end
  resources :retry_review, only: [:show] do
    get ":id", to: "reviews#retry_review", on: :collection
  end
  resources :notifications
  resources :starts do
    collection do
      get :start_transfer
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users
  resources :users, :controller => 'users'
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transfer, only: [:show, :retry_transfer]
  attr_reader :client, :transfer

  # GET /transfers
  def index
    @client = Gush::Client.new
    @transfers = client.all_workflows.select { |wf| wf.class == TransferWorkflow }
  end

  # GET /transfers/1
  def show; end

  # GET /retry_transfer/1
  def retry_transfer
    transfer.continue
    transfer.reload
    respond_to do |format|
      format.html { redirect_to transfer_path, notice: "Transfer #{params[:id]} was sent for a retry." }
      format.json { head :no_content }
    end
  end

  # DELETE /transfers/1
  def destroy
    @client ||= Gush::Client.new
    client.destroy_workflow(client.find_workflow(params[:id]))
    respond_to do |format|
      format.html { redirect_to transfers_path, notice: "Transfer #{params[:id]} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = TransferWorkflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:status)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
  include WorkflowsHelper
end

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<% if @transfers.length > 5 %>
  <p>
    <%= link_to 'Goto Reviews', reviews_path %><br />
    <%= link_to 'Goto Ingests', ingests_path %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Transfer</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Status</th>
      <th>Failure info</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% jobs_in_order(@transfers).each do | transfer | %>
      
      <tr>
        <td>
          <%= transfer.id %><br />
          <%= link_to 'Show', :action => "show", :id => transfer.id %>
          </td>
        <td><%= Time.at(transfer.started_at) unless transfer.started_at.blank? %></td>
        <td><%= Time.at(transfer.finished_at) unless transfer.finished_at.blank? %></td>
        <td><%= transfer.status %></td>
        <td>
          <% transfer.jobs.select(&:failed?).sort_by(&:failed_at).each do | job | %>
            Job: <%= job.name %><br />
            &nbsp;&nbsp;Failed at: <%= Time.at(job.failed_at) %><br />
            &nbsp;&nbsp;Message: <%= job.output_payload[:message] if job.output_payload %>
            <% if job.output_payload && job.output_payload[:event] == 'retry' %>
            <br /><br />
            Event state: <%= job.output_payload[:event] %><br />
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Delete', 
             transfer_path(transfer.id), 
             method: :delete, 
             data: { confirm: 'Are you sure you want to delete this transfer?' } %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<p>
  <%= link_to 'Goto Reviews', reviews_path %><br />
  <%= link_to 'Goto Ingests', ingests_path %>
</p>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<table>

  <tbody>
    <tr>
      <td>ID:</td><td><%= @transfer.id %></td>
    </tr>
    <tr>
      <td>Name:</td><td><%= @transfer.class.to_s %></td>
    </tr>
    <tr>
      <td>Status</td><td><%= @transfer.status %></td>
    </tr>
    <tr>
      <td>Started at:</td><td><%= Time.at(@transfer.started_at) unless @transfer.started_at.blank? %></td>
    </tr>
    <tr>
      <td>Finished at:</td><td><%= Time.at(@transfer.finished_at) unless @transfer.finished_at.blank? %></td>
    </tr>
    <tr>
      <td>Total Jobs:</td><td><%= @transfer.jobs.count %></td>
    </tr>
    <tr>
      <td>Enqueued jobs:</td><td><%= count(@transfer, 'enqueued') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Running jobs:</td><td><%= count(@transfer, 'running') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Remaining jobs:</td><td><%= count(@transfer, 'remaining') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Succeeded jobs:</td><td><%= count(@transfer, 'succeeded') %></td>
    </tr>
    <tr>
      <td>Number of files:</td><td><%= @transfer.number_of_files %> </td>
    </tr>
    <% succeeded_jobs_in_order(@transfer).each do | job |  %>
      <tr>
        <td></td>
        <td>
          <%= job.name %><br />
          <% if job.output_payload %>
            <% job.output_payload.each do | key,value | %>
              <% next if value.blank? %>
              &nbsp;&nbsp;<%= "#{key}: #{value}" %><br />
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>Failed jobs:</td><td><%= @transfer.jobs.select(&:failed?).count %></td>
    </tr>
    <% failed_jobs_in_order(@transfer).each do | job | %>
      <tr>
        <td></td>
        <td>
          <%= job.name %><br />
          <% if job.output_payload %>
            <% job.output_payload.each do | key,value | %>
              <% next if value.blank? %>
              &nbsp;&nbsp;<%= "#{key}: #{value}" %><br />
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to 'Refresh', transfer_path %> |
<%# unless @transfer.finished? %>
  <%= link_to 'Retry', retry_transfer_path(@transfer.id) %> |
<%# end %>
<%= link_to 'Delete',
             transfer_path(@transfer.id),
             method: :delete,
             data: { confirm: 'Are you sure you want to delete this transfer?' } %> |
<%= link_to 'Back', transfers_path %>