config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  
  resources :data_mappers
  resources :workflows, only: [:index]
  resources :ingests, only: [:index, :show, :destroy]
  resources :transfers, only: [:index, :show, :destroy]
  resources :reviews, only: [:index, :show, :destroy]
  
  resources :retry_ingest, only: [:show] do
    get ":id", to: "ingests#retry_ingest", on: :collection
  end
  resources :retry_transfer, only: [:show] do
    get ":id", to: "transfers#retry_transfer", on: :collection
  end
  resources :retry_review, only: [:show] do
    get ":id", to: "reviews#retry_review", on: :collection
  end
  resources :notifications
  resources :starts do
    collection do
      get :start_transfer
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users
  resources :users, :controller => 'users'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :retry_review]
  attr_reader :client, :review

  # GET /reviews
  def index
    @client = Gush::Client.new
    @reviews = client.all_workflows.select { |wf| wf.class == ReviewWorkflow }
  end

  # GET /reviews/1
  def show; end

  # GET /retry_review/1
  def retry_review
    review.continue
    review.reload
    respond_to do |format|
      format.html { redirect_to review_path, notice: "Review #{params[:id]} was sent for a retry." }
      format.json { head :no_content }
    end
  end

  # DELETE /reviews/1
  def destroy
    @client ||= Gush::Client.new
    client.destroy_workflow(client.find_workflow(params[:id]))
    respond_to do |format|
      format.html { redirect_to reviews_path, notice: "Review #{params[:id]} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = ReviewWorkflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:status)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  include WorkflowsHelper
end

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<% if @reviews.length > 5 %>
  <p>
    <%= link_to 'Goto Transfers', transfers_path %><br />
    <%= link_to 'Goto Ingests', ingests_path %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Review</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Status</th>
      <th>Failure info</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% jobs_in_order(@reviews).each do | review | %>
      
      <tr>
        <td>
          <%= review.id %><br />
          <%= link_to 'Show', :action => "show", :id => review.id %>
          </td>
        <td><%= Time.at(review.started_at) unless review.started_at.blank? %></td>
        <td><%= Time.at(review.finished_at) unless review.finished_at.blank? %></td>
        <td><%= review.status %></td>
        <td>
          <% review.jobs.select(&:failed?).sort_by(&:failed_at).each do | job | %>
            Job: <%= job.name %><br />
            &nbsp;&nbsp;Failed at: <%= Time.at(job.failed_at) %><br />
            &nbsp;&nbsp;Message: <%= job.output_payload[:message] if job.output_payload %>
            <% if job.output_payload && job.output_payload[:event] == 'retry' %>
            <br /><br />
            Event state: <%= job.output_payload[:event] %><br />
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Delete', 
             review_path(review.id), 
             method: :delete, 
             data: { confirm: 'Are you sure you want to delete this review?' } %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<p>
  <%= link_to 'Goto Transfers', transfers_path %><br />
  <%= link_to 'Goto Ingests', ingests_path %>
</p>

<br>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<table>

  <tbody>
    <tr>
      <td>ID:</td><td><%= @review.id %></td>
    </tr>
    <tr>
      <td>Name:</td><td><%= @review.class.to_s %></td>
    </tr>
    <tr>
      <td>Status</td><td><%= @review.status %></td>
    </tr>
    <tr>
      <td>Started at:</td><td><%= Time.at(@review.started_at) unless @review.started_at.blank? %></td>
    </tr>
    <tr>
      <td>Finished at:</td><td><%= Time.at(@review.finished_at) unless @review.finished_at.blank? %></td>
    </tr>
    <tr>
      <td>Total Jobs:</td><td><%= @review.jobs.count %></td>
    </tr>
    <tr>
      <td>Enqueued jobs:</td><td><%= count(@review, 'enqueued') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Running jobs:</td><td><%= count(@review, 'running') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Remaining jobs:</td><td><%= count(@review, 'remaining') %></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;Succeeded jobs:</td><td><%= count(@review, 'succeeded') %></td>
    </tr>
    <% succeeded_jobs_in_order(@review).each do | job |  %>
      <tr>
        <td></td>
        <td>
          <%= job.name %><br />
          <% if job.output_payload %>
            <% job.output_payload.each do | key,value | %>
              <% next if value.blank? %>
              &nbsp;&nbsp;<%= "#{key}: #{value}" %><br />
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>Failed jobs:</td><td><%= @review.jobs.select(&:failed?).count %></td>
    </tr>
    <% failed_jobs_in_order(@review).each do | job | %>
      <tr>
        <td></td>
        <td>
          <%= job.name %><br />
          <% if job.output_payload %>
            <% job.output_payload.each do | key,value | %>
              <% next if value.blank? %>
              &nbsp;&nbsp;<%= "#{key}: #{value}" %><br />
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to 'Refresh', review_path %> |
<% unless @review.finished? %>
  <%= link_to 'Retry', retry_review_path(@review.id) %> |
<% end %>
<%= link_to 'Delete',
             review_path(@review.id),
             method: :delete,
             data: { confirm: 'Are you sure you want to delete this review?' } %> |
<%= link_to 'Back', reviews_path %>